### ISSUE TITLE
Challenge - Lightswitch Bug

### ISSUE THREAD

**Issue by sfeichtenschlager** [htl-leo-itp-2325-4-5BHITM/EcoHome#82]
In der Abschlusspräsentation wurde nach dem Linear Mode der Challenge Mode gestartet, wobei sich beim Nutzen eines Lichtschalters die Unity Ausführung pausierte. Der Fehler soll gefunden, nachgebildet und gefixt werden!

## Def. of Done

Der Fehler tritt nicht mehr auf.

**Comment by Skywocoder** [comment]
Bug was not found in current Testing
